copyright: Copyright (c) Ultraviolet
repo_url: https://github.com/ultravioletrs/cocos
site_description: Prism Platform
site_name: Cocos
site_url: https://docs.cocos.ai
edit_uri: ""
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Billing: billing.md
  - Computations: computations.md
  - Users: users.md
  - Projectss: projects.md
  - UI: ui.md
  - Computation Policies: policies.md
  - Certs: certs.md
  - Backends: backends.md
